spring:
  application:
    name: eureka-server

server:
  port: 8141

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  file: ${spring.application.name}.log
