spring:
  application:
    name: eureka-server
  security:
    user:
      name: meijie
      password: 870725

server:
  port: 8141

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
