server:
  port: 8143

spring:
  application:
    name: Eureka-Server

eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      default-zone: http://peer1:8142/eureka/
  server:
    enable-self-preservation: false